### ISSUE TITLE
Podcasting Namespace implementation status overview

### ISSUE THREAD

**Issue by saerdnaer** [podlove/podlove-publisher#1242]
This list tries to give an overview about 
the individual tags of the [Podcast Namespace]( https://github.com/Podcastindex-org/podcast-namespace#element) in Podlove Publisher:

"Test" Feed: `https://feeds.podlovers.org/mp3`

### Phase 1 (Closed on November 2020)

The following tags have been formally adopted into the namespace.  They are fully documented in the XMLNS document located [here](https://github.com/Podcastindex-org/podcast-namespace/docs/1.0.md).  Please see that file for
full implementation details.

- [ ] **\<podcast:locked>** 
- [x] **\<podcast:transcript>** 
- [x]  **\<podcast:funding>** 
- [ ] **\<podcast:chapters>** duplicates `<psc:chapters …>`
- [x] **\<podcast:soundbite>** 3.6.0

### Phase 2 (Closed on January 2021)

The following tags have been formally adopted into the namespace.  They are fully documented in the XMLNS document located [here](https://github.com/Podcastindex-org/podcast-namespace/docs/1.0.md).  Please see that file for full implementation details.

- [x] **\<podcast:person>** will replace  `<atom:contributor>`, `href` attribute still missing, c.f. https://github.com/podlove/podlove-publisher/pull/1195
- [ ] **\<podcast:location>**
- [ ] **\<podcast:season>** duplicates `<itunes:season>`
- [ ] **\<podcast:episode>** duplicates `<itunes:episode>`

### Phase 3 (Closed on June 2021)

The following tags have been formally adopted into the namespace.  They are fully documented in the XMLNS document located [here](https://github.com/Podcastindex-org/podcast-namespace/docs/1.0.md).  Please see that file for full implementation details.

- [ ] **\<podcast:trailer>**
- [ ] **\<podcast:license>**
- [ ] **\<podcast:alternateEnclosure>** 
  - [ ] **\<podcast:source>** 
  - [ ] **\<podcast:integrity>** 
- [ ] **\<podcast:guid>** 

### Phase 4 (Closes on 2022-12-01)

The following tags should be considered purely as work in progress proposals.  They should not be relied upon or implemented except for testing purposes and experimentation.

see https://github.com/Podcastindex-org/podcast-namespace/blob/main/README.md#phase-4-closes-on-1212021
